# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-02 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chirp',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='chirp',
            name='content3',
        ),
    ]
